using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EnumWrapper.SourceGenerators
{
    internal static class CodeWriter
    {
        /// <summary>
        /// Formats XML documentation comment for inclusion in generated source code.
        /// </summary>
        private static string FormatXmlDocumentation(string xmlComment, string indent)
        {
            if (string.IsNullOrEmpty(xmlComment)) return "";
            try
            {
                var doc = new System.Xml.XmlDocument();
                doc.LoadXml(xmlComment);
                var summaryNode = doc.SelectSingleNode("//summary");
                if (summaryNode != null)
                {
                    var text = summaryNode.InnerXml.Trim();
                    var lines = text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                    var sb = new StringBuilder();
                    sb.AppendLine($"{indent}/// <summary>");
                    foreach (var line in lines)
                    {
                        sb.AppendLine($"{indent}/// {line.Trim()}");
                    }
                    sb.AppendLine($"{indent}/// </summary>");
                    return sb.ToString();
                }
            }
            catch (System.Xml.XmlException)
            {
                // Invalid XML from the compiler is not actionable here; skip silently.
            }

            return "";
        }

        public static void GenerateWrapper(SourceProductionContext context, EnumToWrapInfo enumInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(enumInfo.WrapperNamespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {enumInfo.WrapperNamespace}");
                sb.AppendLine("{");
            }

            var indent = hasNamespace ? "    " : "";

            // Copy Class XML Documentation
            var classDocs = FormatXmlDocumentation(enumInfo.XmlDocumentation, indent);
            if (!string.IsNullOrEmpty(classDocs))
            {
                sb.Append(classDocs);
            }

            // Decorate with System.ComponentModel.TypeConverter for XAML direct string assignment support
            sb.AppendLine($"{indent}[System.ComponentModel.TypeConverter(typeof({enumInfo.WrapperClassName}TypeConverter))]");

            // If System.Text.Json is available, decorate with custom JsonConverter
            if (enumInfo.HasJson)
            {
                sb.AppendLine($"{indent}[System.Text.Json.Serialization.JsonConverter(typeof({enumInfo.WrapperClassName}JsonConverter))]");
            }

            sb.AppendLine($"{indent}public partial class {enumInfo.WrapperClassName} : IEquatable<{enumInfo.WrapperClassName}>");
            sb.AppendLine($"{indent}{{");

            // Properties
            sb.AppendLine($"{indent}    /// <summary>The wrapped enum value.</summary>");
            sb.AppendLine($"{indent}    public {enumInfo.EnumFullName} Value {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>The human-readable description retrieved from description/display attributes.</summary>");
            sb.AppendLine($"{indent}    public string Description {{ get; }}");
            sb.AppendLine();

            bool hasShortName = enumInfo.Members.Any(m => m.ShortName != null);
            if (hasShortName)
            {
                sb.AppendLine($"{indent}    /// <summary>The short name specified in DisplayAttribute (for UI display when space is limited).</summary>");
                sb.AppendLine($"{indent}    public string? ShortName {{ get; }}");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}    /// <summary>The group name specified in DisplayAttribute (for UI categorization).</summary>");
            sb.AppendLine($"{indent}    public string? GroupName {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>The numeric representation of the enum value cast to its underlying type.</summary>");
            sb.AppendLine($"{indent}    public {enumInfo.UnderlyingTypeName} UnderlyingValue => ({enumInfo.UnderlyingTypeName})Value;");
            sb.AppendLine();

            // Constructor
            var ctorParams = hasShortName
                ? $"{enumInfo.EnumFullName} value, string description, string? shortName, string? groupName"
                : $"{enumInfo.EnumFullName} value, string description, string? groupName";

            sb.AppendLine($"{indent}    private {enumInfo.WrapperClassName}({ctorParams})");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        Value = value;");
            sb.AppendLine($"{indent}        Description = description;");
            if (hasShortName)
            {
                sb.AppendLine($"{indent}        ShortName = shortName;");
            }
            sb.AppendLine($"{indent}        GroupName = groupName;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ToString() override
            sb.AppendLine($"{indent}    public override string ToString() => Description;");
            sb.AppendLine();

            // IEquatable implementation
            sb.AppendLine($"{indent}    public bool Equals({enumInfo.WrapperClassName}? other)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (other is null) return false;");
            sb.AppendLine($"{indent}        if (ReferenceEquals(this, other)) return true;");
            sb.AppendLine($"{indent}        return Value == other.Value;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            sb.AppendLine($"{indent}    public override bool Equals(object? obj) => Equals(obj as {enumInfo.WrapperClassName});");
            sb.AppendLine($"{indent}    public override int GetHashCode() => Value.GetHashCode();");
            sb.AppendLine();

            // Equality operators
            sb.AppendLine($"{indent}    public static bool operator ==({enumInfo.WrapperClassName}? left, {enumInfo.WrapperClassName}? right) => Equals(left, right);");
            sb.AppendLine($"{indent}    public static bool operator !=({enumInfo.WrapperClassName}? left, {enumInfo.WrapperClassName}? right) => !Equals(left, right);");
            sb.AppendLine();

            // Implicit operator to enum type
            sb.AppendLine($"{indent}    public static implicit operator {enumInfo.EnumFullName}({enumInfo.WrapperClassName}? wrapper) => wrapper?.Value ?? default;");
            sb.AppendLine();

            // Static items array
            sb.AppendLine($"{indent}    /// <summary>Provides the sorted, read-only list of all generated enum wrappers.</summary>");
            sb.AppendLine($"{indent}    public static IReadOnlyList<{enumInfo.WrapperClassName}> Items {{ get; }} = new {enumInfo.WrapperClassName}[]");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < enumInfo.Members.Length; i++)
            {
                var member = enumInfo.Members[i];
                var escapedDesc = member.Description.Replace("\\", "\\\\").Replace("\"", "\\\"");
                var escapedGroup = member.GroupName != null ? $"\"{member.GroupName.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"" : "null";
                var escapedShortName = member.ShortName != null ? $"\"{member.ShortName.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"" : "null";

                // Copy Member XML Documentation onto each static instantiation
                var memberDocs = FormatXmlDocumentation(member.XmlDocumentation, indent + "        ");
                if (!string.IsNullOrEmpty(memberDocs))
                {
                    sb.Append(memberDocs);
                }

                if (hasShortName)
                {
                    sb.AppendLine($"{indent}        new {enumInfo.WrapperClassName}({enumInfo.EnumFullName}.{member.Name}, \"{escapedDesc}\", {escapedShortName}, {escapedGroup}),");
                }
                else
                {
                    sb.AppendLine($"{indent}        new {enumInfo.WrapperClassName}({enumInfo.EnumFullName}.{member.Name}, \"{escapedDesc}\", {escapedGroup}),");
                }
            }
            sb.AppendLine($"{indent}    }};");
            sb.AppendLine();

            // Optimized O(1) Index Lookup or Dictionary mapping
            if (enumInfo.IsContiguous)
            {
                // Items is sorted by DisplayAttribute.Order (for UI binding).
                // _byValue is sorted by numeric value index for correct O(1) FromValue.
                sb.AppendLine($"{indent}    private static readonly {enumInfo.WrapperClassName}[] _byValue = new {enumInfo.WrapperClassName}[]");
                sb.AppendLine($"{indent}    {{");
                var count = enumInfo.Members.Length;
                // Create a mapping: numeric value → index in Items (which is sorted by Display.Order)
                var itemsOrder = enumInfo.Members.OrderBy(m => m.Order ?? int.MaxValue).ToArray();
                var valueToItemsIndex = new int[count];
                for (int v = 0; v < count; v++)
                {
                    for (int j = 0; j < itemsOrder.Length; j++)
                    {
                        if (itemsOrder[j].NumericValue == v)
                        {
                            valueToItemsIndex[v] = j;
                            break;
                        }
                    }
                }
                for (int v = 0; v < count; v++)
                {
                    var itemsIdx = valueToItemsIndex[v];
                    sb.AppendLine($"{indent}        Items[{itemsIdx}],");
                }
                sb.AppendLine($"{indent}    }};");
                sb.AppendLine();
                sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value in O(1) speed.</summary>");
                sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        int index = (int)value;");
                sb.AppendLine($"{indent}        if (index >= 0 && index < _byValue.Length)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return _byValue[index];");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, value.ToString(), null{(hasShortName ? ", null" : "")});");
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                // Caching Dictionary (fallback for non-contiguous or Flags enums)
                sb.AppendLine($"{indent}    private static readonly Dictionary<{enumInfo.EnumFullName}, {enumInfo.WrapperClassName}> _map = new Dictionary<{enumInfo.EnumFullName}, {enumInfo.WrapperClassName}>");
                sb.AppendLine($"{indent}    {{");
                for (int i = 0; i < enumInfo.Members.Length; i++)
                {
                    var member = enumInfo.Members[i];
                    sb.AppendLine($"{indent}        {{ {enumInfo.EnumFullName}.{member.Name}, Items[{i}] }},");
                }
                sb.AppendLine($"{indent}    }};");
                sb.AppendLine();

                if (enumInfo.IsFlags)
                {
                    sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value, supporting combined flags.</summary>");
                    sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        if (_map.TryGetValue(value, out var wrapper))");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return wrapper;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        var desc = ComputeFlagsDescription(value);");
                    sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, desc, null{(hasShortName ? ", null" : "")});");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();

                    // Compute flags description dynamic helper
                    sb.AppendLine($"{indent}    private static string ComputeFlagsDescription({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var parts = new List<string>();");
                    sb.AppendLine($"{indent}        foreach (var item in Items)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            if (item.Value.Equals(default({enumInfo.EnumFullName})))");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                if (value.Equals(default({enumInfo.EnumFullName})))");
                    sb.AppendLine($"{indent}                {{");
                    sb.AppendLine($"{indent}                    return item.Description;");
                    sb.AppendLine($"{indent}                }}");
                    sb.AppendLine($"{indent}                continue;");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}            if ((({enumInfo.UnderlyingTypeName})value & ({enumInfo.UnderlyingTypeName})item.Value) == ({enumInfo.UnderlyingTypeName})item.Value)");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                parts.Add(item.Description);");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        if (parts.Count > 0)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return string.Join(\", \", parts);");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        return value.ToString();");
                    sb.AppendLine($"{indent}    }}");
                }
                else
                {
                    sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value.</summary>");
                    sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        if (_map.TryGetValue(value, out var wrapper))");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return wrapper;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, value.ToString(), null{(hasShortName ? ", null" : "")});");
                    sb.AppendLine($"{indent}    }}");
                }
            }
            sb.AppendLine();

            // Smart Parsing: TryParse and Parse (single-pass matching)
            sb.AppendLine($"{indent}    /// <summary>Attempts to parse a string representation (by description or name) to its wrapper object.</summary>");
            sb.AppendLine($"{indent}    public static bool TryParse(string? text, out {enumInfo.WrapperClassName}? result)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        result = null;");
            sb.AppendLine($"{indent}        if (string.IsNullOrEmpty(text)) return false;");
            sb.AppendLine();
            sb.AppendLine($"{indent}        // 1. Match by Description or Enum Name (single pass)");
            sb.AppendLine($"{indent}        foreach (var item in Items)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (string.Equals(item.Description, text, StringComparison.OrdinalIgnoreCase) ||");
            sb.AppendLine($"{indent}                string.Equals(item.Value.ToString(), text, StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                result = item;");
            sb.AppendLine($"{indent}                return true;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        // 2. Native Enum Parse");
            sb.AppendLine($"{indent}        if (Enum.TryParse<{enumInfo.EnumFullName}>(text, true, out var parsedValue))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            result = FromValue(parsedValue);");
            sb.AppendLine($"{indent}            return true;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        return false;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            sb.AppendLine($"{indent}    /// <summary>Parses a string representation (by description or name) to its wrapper object.</summary>");
            sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} Parse(string text)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (TryParse(text, out var result))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            return result!;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}        throw new ArgumentException($\"Requested value '{{text}}' was not found in {enumInfo.EnumFullName} wrapper.\");");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // Flags specific bitwise helpers
            if (enumInfo.IsFlags)
            {
                sb.AppendLine($"{indent}    /// <summary>Checks if a specific flag is set.</summary>");
                sb.AppendLine($"{indent}    public bool HasFlag({enumInfo.EnumFullName} flag) => Value.HasFlag(flag);");
                sb.AppendLine($"{indent}    /// <summary>Checks if a specific flag is set.</summary>");
                sb.AppendLine($"{indent}    public bool HasFlag({enumInfo.WrapperClassName} wrapper) => wrapper != null && Value.HasFlag(wrapper.Value);");
                sb.AppendLine();

                sb.AppendLine($"{indent}    /// <summary>Flattens the active flags of this combination into separate single wrapper elements.</summary>");
                sb.AppendLine($"{indent}    public IEnumerable<{enumInfo.WrapperClassName}> GetFlags()");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        foreach (var item in Items)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (item.Value.Equals(default({enumInfo.EnumFullName}))) continue;");
                sb.AppendLine($"{indent}            if (HasFlag(item.Value))");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                yield return item;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();
            }

            // TypeConverter implementation
            sb.AppendLine($"{indent}    [System.ComponentModel.DisplayName(\"{enumInfo.WrapperClassName} Type Converter\")]");
            sb.AppendLine($"{indent}    public class {enumInfo.WrapperClassName}TypeConverter : System.ComponentModel.TypeConverter");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (value is string str)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                if ({enumInfo.WrapperClassName}.TryParse(str, out var result))");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"                    return result;");
            sb.AppendLine($"                }}");
            sb.AppendLine($"{indent}                throw new ArgumentException($\"Cannot convert '{{str}}' to {enumInfo.WrapperClassName}.\");");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            return base.ConvertFrom(context, culture, value);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // Nested JSON Converter (conditional on System.Text.Json dependency)
            if (enumInfo.HasJson)
            {
                sb.AppendLine($"{indent}    public class {enumInfo.WrapperClassName}JsonConverter : System.Text.Json.Serialization.JsonConverter<{enumInfo.WrapperClassName}>");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        public override {enumInfo.WrapperClassName} Read(ref System.Text.Json.Utf8JsonReader reader, Type typeToConvert, System.Text.Json.JsonSerializerOptions options)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (reader.TokenType == System.Text.Json.JsonTokenType.String)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"                var str = reader.GetString();");
                sb.AppendLine($"                if (TryParse(str, out var result))");
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    return result!;");
                sb.AppendLine($"                }}");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            else if (reader.TokenType == System.Text.Json.JsonTokenType.Number)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                if (reader.TryGetInt64(out var num))");
                sb.AppendLine($"{indent}                {{");
                sb.AppendLine($"                    return FromValue(({enumInfo.EnumFullName})num);");
                sb.AppendLine($"{indent}                }}");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            throw new System.Text.Json.JsonException($\"Cannot deserialize {enumInfo.WrapperClassName} from current token.\");");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine();
                sb.AppendLine($"{indent}        public override void Write(System.Text.Json.Utf8JsonWriter writer, {enumInfo.WrapperClassName} value, System.Text.Json.JsonSerializerOptions options)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (value == null)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                writer.WriteNullValue();");
                sb.AppendLine($"{indent}                return;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            writer.WriteStringValue(value.Value.ToString());");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }

            sb.AppendLine($"{indent}}}"); // Class

            // Generate companion WPF IValueConverter (conditional on WPF dependency check)
            if (enumInfo.HasWpf)
            {
                // Use EnumName (without "Wrapper" suffix) for clean converter naming
                var converterClassName = $"{enumInfo.EnumName}ToWrapperConverter";
                sb.AppendLine();
                sb.AppendLine($"{indent}/// <summary>WPF ValueConverter to map {enumInfo.EnumName} value and {enumInfo.WrapperClassName} back and forth in XAML.</summary>");
                sb.AppendLine($"{indent}public class {converterClassName} : System.Windows.Data.IValueConverter");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    /// <summary>Singleton instance of the converter.</summary>");
                sb.AppendLine($"{indent}    public static {converterClassName} Instance {{ get; }} = new {converterClassName}();");
                sb.AppendLine();
                sb.AppendLine($"{indent}    public object? Convert(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        if (value is {enumInfo.EnumFullName} enumValue)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return {enumInfo.WrapperClassName}.FromValue(enumValue);");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        if (value is string str && {enumInfo.WrapperClassName}.TryParse(str, out var result))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return result;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return null;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();
                sb.AppendLine($"{indent}    public object? ConvertBack(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        if (value is {enumInfo.WrapperClassName} wrapper)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return wrapper.Value;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        if (value is {enumInfo.EnumFullName} enumValue)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return enumValue;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return null;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}}}");
            }

            if (hasNamespace)
            {
                sb.AppendLine("}"); // Namespace
            }

            var sourceName = $"{enumInfo.WrapperNamespace}.{enumInfo.WrapperClassName}.g.cs";
            context.AddSource(sourceName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
