using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EnumWrapper.SourceGenerators
{
    [Generator]
    public class EnumWrapperSourceGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

using System;

namespace EnumWrapper.SourceGenerators
{
    [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateEnumWrapperAttribute : Attribute
    {
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }
    }

    [AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = true)]
    internal sealed class GenerateEnumWrapperForAttribute : Attribute
    {
        public Type EnumType { get; }
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }

        public GenerateEnumWrapperForAttribute(Type enumType)
        {
            EnumType = enumType;
        }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Post-initialization to inject attributes
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "GenerateEnumWrapperAttributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

            // 2. Syntax provider for local enums
            var localEnums = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is BaseTypeDeclarationSyntax,
                transform: static (ctx, cancellationToken) => EnumInfoExtractor.GetEnumToWrap(ctx, cancellationToken)
            ).Where(static x => x is not null);

            // 3. Compilation provider for assembly level attributes
            var assemblyEnums = context.CompilationProvider.Select((compilation, cancellationToken) =>
                EnumInfoExtractor.GetAssemblyEnumsToWrap(compilation, cancellationToken));

            var assemblyEnumsFlat = assemblyEnums.SelectMany((list, _) => list);

            // 4. Register output generation
            context.RegisterSourceOutput(localEnums, static (spc, result) =>
            {
                if (result!.Diagnostic != null)
                {
                    var desc = new DiagnosticDescriptor(
                        result.Diagnostic.Id,
                        "EnumWrapper.SourceGenerators Error",
                        result.Diagnostic.Message,
                        "Usage",
                        result.Diagnostic.Severity,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(desc, result.Diagnostic.Location));
                    return;
                }
                if (result.Value != null)
                {
                    CodeWriter.GenerateWrapper(spc, result.Value);
                }
            });

            context.RegisterSourceOutput(assemblyEnumsFlat, static (spc, result) =>
            {
                if (result!.Diagnostic != null)
                {
                    var desc = new DiagnosticDescriptor(
                        result.Diagnostic.Id,
                        "EnumWrapper.SourceGenerators Error",
                        result.Diagnostic.Message,
                        "Usage",
                        result.Diagnostic.Severity,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(desc, result.Diagnostic.Location));
                    return;
                }
                if (result.Value != null)
                {
                    CodeWriter.GenerateWrapper(spc, result.Value);
                }
            });
        }
    }
}
