using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EnumWrapper.SourceGenerators
{
    [Generator]
    public class EnumWrapperSourceGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

using System;

namespace EnumWrapper.SourceGenerators
{
    [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateEnumWrapperAttribute : Attribute
    {
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }
    }

    [AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = true)]
    internal sealed class GenerateEnumWrapperForAttribute : Attribute
    {
        public Type EnumType { get; }
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }

        public GenerateEnumWrapperForAttribute(Type enumType)
        {
            EnumType = enumType;
        }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Post-initialization to inject attributes
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "GenerateEnumWrapperAttributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

            // 2. Attribute-based provider for local declarations
            var localEnums = context.SyntaxProvider.ForAttributeWithMetadataName(
                "EnumWrapper.SourceGenerators.GenerateEnumWrapperAttribute",
                predicate: static (node, _) => node is BaseTypeDeclarationSyntax,
                transform: static (ctx, cancellationToken) => EnumInfoExtractor.GetEnumToWrap(ctx, cancellationToken)
            )
            .Where(static x => x is not null)
            .Select(static (result, _) => result!);

            // 3. Compilation provider for assembly level attributes
            var assemblyEnums = context.CompilationProvider.Select((compilation, cancellationToken) =>
                EnumInfoExtractor.GetAssemblyEnumsToWrap(compilation, cancellationToken));

            // 4. Register output generation
            context.RegisterSourceOutput(localEnums.Collect().Combine(assemblyEnums), static (spc, source) =>
            {
                GenerationPlanner.EmitSources(spc, source.Left, source.Right);
            });
        }
    }
}
