using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EnumWrapper.SourceGenerators
{
    [Generator]
    public class EnumWrapperSourceGenerator : IIncrementalGenerator
    {
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable

using System;

namespace EnumWrapper.SourceGenerators
{
    [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
    internal sealed class GenerateEnumWrapperAttribute : Attribute
    {
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }
    }

    [AttributeUsage(AttributeTargets.Assembly, Inherited = false, AllowMultiple = true)]
    internal sealed class GenerateEnumWrapperForAttribute : Attribute
    {
        public Type EnumType { get; }
        public string? WrapperClassName { get; set; }
        public string? CustomNamespace { get; set; }

        public GenerateEnumWrapperForAttribute(Type enumType)
        {
            EnumType = enumType;
        }
    }
}
";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 1. Post-initialization to inject attributes
            context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
                "GenerateEnumWrapperAttributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

            // 2. Syntax provider for local enums
            var localEnums = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is BaseTypeDeclarationSyntax,
                transform: static (ctx, cancellationToken) => GetEnumToWrap(ctx, cancellationToken)
            ).Where(static x => x is not null);

            // 3. Compilation provider for assembly level attributes
            var assemblyEnums = context.CompilationProvider.Select((compilation, cancellationToken) => 
                GetAssemblyEnumsToWrap(compilation, cancellationToken));

            var assemblyEnumsFlat = assemblyEnums.SelectMany((list, _) => list);

            // 4. Register output generation
            context.RegisterSourceOutput(localEnums, static (spc, result) =>
            {
                if (result!.Diagnostic != null)
                {
                    var desc = new DiagnosticDescriptor(
                        result.Diagnostic.Id,
                        "EnumWrapper.SourceGenerators Error",
                        result.Diagnostic.Message,
                        "Usage",
                        result.Diagnostic.Severity,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(desc, result.Diagnostic.Location));
                    return;
                }
                if (result.Value != null)
                {
                    GenerateWrapper(spc, result.Value);
                }
            });

            context.RegisterSourceOutput(assemblyEnumsFlat, static (spc, result) =>
            {
                if (result!.Diagnostic != null)
                {
                    var desc = new DiagnosticDescriptor(
                        result.Diagnostic.Id,
                        "EnumWrapper.SourceGenerators Error",
                        result.Diagnostic.Message,
                        "Usage",
                        result.Diagnostic.Severity,
                        isEnabledByDefault: true);
                    spc.ReportDiagnostic(Diagnostic.Create(desc, result.Diagnostic.Location));
                    return;
                }
                if (result.Value != null)
                {
                    GenerateWrapper(spc, result.Value);
                }
            });
        }

        private static GeneratorResult<EnumToWrapInfo>? GetEnumToWrap(GeneratorSyntaxContext ctx, CancellationToken cancellationToken)
        {
            var typeDeclaration = (BaseTypeDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken) as INamedTypeSymbol;
            if (symbol is null) return null;

            AttributeData? targetAttr = null;
            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass is { } attrClass &&
                    attrClass.ToDisplayString() == "EnumWrapper.SourceGenerators.GenerateEnumWrapperAttribute")
                {
                    targetAttr = attr;
                    break;
                }
            }

            if (targetAttr == null) return null;

            // EWG001: Applied to a non-enum type
            if (symbol.TypeKind != TypeKind.Enum)
            {
                var location = typeDeclaration.Identifier.GetLocation();
                var diag = new DiagnosticInfo(
                    "EWG001",
                    $"The [GenerateEnumWrapper] attribute can only be applied to enum types. '{symbol.Name}' is a {symbol.TypeKind.ToString().ToLower()}.",
                    DiagnosticSeverity.Error,
                    location
                );
                return new GeneratorResult<EnumToWrapInfo>(diag);
            }

            string? wrapperClassName = null;
            string? customNamespace = null;
            foreach (var namedArg in targetAttr.NamedArguments)
            {
                if (namedArg.Key == "WrapperClassName")
                    wrapperClassName = namedArg.Value.Value as string;
                else if (namedArg.Key == "CustomNamespace")
                    customNamespace = namedArg.Value.Value as string;
            }

            var compilation = ctx.SemanticModel.Compilation;
            var hasJson = compilation.GetTypeByMetadataName("System.Text.Json.Serialization.JsonConverterAttribute") != null;
            var hasWpf = compilation.GetTypeByMetadataName("System.Windows.Data.IValueConverter") != null;

            var info = ExtractEnumInfo(symbol, wrapperClassName, customNamespace, hasJson, hasWpf);
            return new GeneratorResult<EnumToWrapInfo>(info);
        }

        private static ImmutableArray<GeneratorResult<EnumToWrapInfo>> GetAssemblyEnumsToWrap(Compilation compilation, CancellationToken cancellationToken)
        {
            var list = ImmutableArray.CreateBuilder<GeneratorResult<EnumToWrapInfo>>();
            var attributes = compilation.Assembly.GetAttributes();
            var hasJson = compilation.GetTypeByMetadataName("System.Text.Json.Serialization.JsonConverterAttribute") != null;
            var hasWpf = compilation.GetTypeByMetadataName("System.Windows.Data.IValueConverter") != null;

            foreach (var attr in attributes)
            {
                if (cancellationToken.IsCancellationRequested) break;

                if (attr.AttributeClass is { } attrClass &&
                    attrClass.ToDisplayString() == "EnumWrapper.SourceGenerators.GenerateEnumWrapperForAttribute")
                {
                    if (attr.ConstructorArguments.Length > 0)
                    {
                        var typeArg = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
                        
                        // EWG002: Targeted type is not an enum
                        if (typeArg == null || typeArg.TypeKind != TypeKind.Enum)
                        {
                            var location = attr.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation() ?? Location.None;
                            var targetedName = typeArg?.Name ?? "unknown";
                            var diag = new DiagnosticInfo(
                                "EWG002",
                                $"The targeted type of GenerateEnumWrapperFor must be an enum. '{targetedName}' is not an enum.",
                                DiagnosticSeverity.Error,
                                location
                            );
                            list.Add(new GeneratorResult<EnumToWrapInfo>(diag));
                            continue;
                        }

                        string? wrapperClassName = null;
                        string? customNamespace = null;
                        foreach (var namedArg in attr.NamedArguments)
                        {
                            if (namedArg.Key == "WrapperClassName")
                                wrapperClassName = namedArg.Value.Value as string;
                            else if (namedArg.Key == "CustomNamespace")
                                customNamespace = namedArg.Value.Value as string;
                        }

                        var info = ExtractEnumInfo(typeArg, wrapperClassName, customNamespace, hasJson, hasWpf);
                        list.Add(new GeneratorResult<EnumToWrapInfo>(info));
                    }
                }
            }
            return list.ToImmutable();
        }

        private static EnumToWrapInfo ExtractEnumInfo(INamedTypeSymbol enumSymbol, string? wrapperClassName, string? customNamespace, bool hasJson, bool hasWpf)
        {
            var enumName = enumSymbol.Name;
            var enumNamespace = enumSymbol.ContainingNamespace.IsGlobalNamespace
                ? ""
                : enumSymbol.ContainingNamespace.ToDisplayString();

            var enumFullName = enumSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            
            var targetNamespace = customNamespace ?? enumNamespace;
            if (string.IsNullOrEmpty(targetNamespace))
            {
                targetNamespace = "EnumWrapper.SourceGenerators.Generated";
            }

            var targetClassName = wrapperClassName ?? $"{enumName}Wrapper";

            // Detect underlying type
            var underlyingTypeName = "int";
            var underlyingType = enumSymbol.EnumUnderlyingType;
            if (underlyingType != null)
            {
                underlyingTypeName = underlyingType.SpecialType switch
                {
                    SpecialType.System_Byte => "byte",
                    SpecialType.System_SByte => "sbyte",
                    SpecialType.System_Int16 => "short",
                    SpecialType.System_UInt16 => "ushort",
                    SpecialType.System_Int32 => "int",
                    SpecialType.System_UInt32 => "uint",
                    SpecialType.System_Int64 => "long",
                    SpecialType.System_UInt64 => "ulong",
                    _ => underlyingType.ToDisplayString()
                };
            }

            // Detect Flags attribute
            var isFlags = enumSymbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "System.FlagsAttribute");

            // Extract original XML docs
            var enumXmlDocs = enumSymbol.GetDocumentationCommentXml() ?? "";

            var members = new List<EnumMemberInfo>();
            foreach (var member in enumSymbol.GetMembers())
            {
                if (member is IFieldSymbol field && field.ConstantValue != null)
                {
                    var description = field.Name;
                    int? order = null;
                    string? groupName = null;

                    foreach (var attr in field.GetAttributes())
                    {
                        var attrClassName = attr.AttributeClass?.ToDisplayString();
                        if (attrClassName == "System.ComponentModel.DescriptionAttribute")
                        {
                            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string desc)
                            {
                                description = desc;
                            }
                        }
                        else if (attrClassName == "System.ComponentModel.DataAnnotations.DisplayAttribute")
                        {
                            foreach (var namedArg in attr.NamedArguments)
                            {
                                if (namedArg.Key == "Name" && namedArg.Value.Value is string name)
                                {
                                    description = name;
                                }
                                else if (namedArg.Key == "GroupName" && namedArg.Value.Value is string group)
                                {
                                    groupName = group;
                                }
                                else if (namedArg.Key == "Order" && namedArg.Value.Value is int ord)
                                {
                                    order = ord;
                                }
                            }
                        }
                    }

                    var numericVal = Convert.ToInt64(field.ConstantValue);
                    var fieldXmlDocs = field.GetDocumentationCommentXml() ?? "";
                    members.Add(new EnumMemberInfo(field.Name, description, order, groupName, numericVal, fieldXmlDocs));
                }
            }

            // Perform Compile-Time Sorting: Order by 'Order' ascending (null values are sorted last)
            var sortedMembers = members
                .OrderBy(m => m.Order ?? int.MaxValue)
                .ToList();

            // Detect contiguity starting from 0 (Flags enums are naturally not contiguous)
            bool isContiguous = true;
            if (sortedMembers.Count == 0 || isFlags)
            {
                isContiguous = false;
            }
            else
            {
                // Sort by numeric value to check contiguity
                var sortedByValue = sortedMembers.OrderBy(m => m.NumericValue).ToList();
                for (int i = 0; i < sortedByValue.Count; i++)
                {
                    if (sortedByValue[i].NumericValue != i)
                    {
                        isContiguous = false;
                        break;
                    }
                }
            }

            return new EnumToWrapInfo(
                enumNamespace,
                enumName,
                enumFullName,
                targetClassName,
                targetNamespace,
                sortedMembers,
                underlyingTypeName,
                isFlags,
                hasJson,
                isContiguous,
                enumXmlDocs,
                hasWpf
            );
        }

        private static string FormatXmlDocumentation(string xmlComment, string indent)
        {
            if (string.IsNullOrEmpty(xmlComment)) return "";
            try
            {
                var doc = new System.Xml.XmlDocument();
                doc.LoadXml(xmlComment);
                var summaryNode = doc.SelectSingleNode("//summary");
                if (summaryNode != null)
                {
                    var text = summaryNode.InnerXml.Trim();
                    var lines = text.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);
                    var sb = new StringBuilder();
                    sb.AppendLine($"{indent}/// <summary>");
                    foreach (var line in lines)
                    {
                        sb.AppendLine($"{indent}/// {line.Trim()}");
                    }
                    sb.AppendLine($"{indent}/// </summary>");
                    return sb.ToString();
                }
            }
            catch
            {
                // Ignore invalid XML
            }
            return "";
        }

        private static void GenerateWrapper(SourceProductionContext context, EnumToWrapInfo enumInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine();

            bool hasNamespace = !string.IsNullOrEmpty(enumInfo.WrapperNamespace);
            if (hasNamespace)
            {
                sb.AppendLine($"namespace {enumInfo.WrapperNamespace}");
                sb.AppendLine("{");
            }

            var indent = hasNamespace ? "    " : "";

            // Copy Class XML Documentation
            var classDocs = FormatXmlDocumentation(enumInfo.XmlDocumentation, indent);
            if (!string.IsNullOrEmpty(classDocs))
            {
                sb.Append(classDocs);
            }

            // Decorate with System.ComponentModel.TypeConverter for XAML direct string assignment support
            sb.AppendLine($"{indent}[System.ComponentModel.TypeConverter(typeof({enumInfo.WrapperClassName}TypeConverter))]");

            // If System.Text.Json is available, decorate with custom JsonConverter
            if (enumInfo.HasJson)
            {
                sb.AppendLine($"{indent}[System.Text.Json.Serialization.JsonConverter(typeof({enumInfo.WrapperClassName}JsonConverter))]");
            }

            sb.AppendLine($"{indent}public partial class {enumInfo.WrapperClassName} : IEquatable<{enumInfo.WrapperClassName}>");
            sb.AppendLine($"{indent}{{");

            // Properties
            sb.AppendLine($"{indent}    /// <summary>The wrapped enum value.</summary>");
            sb.AppendLine($"{indent}    public {enumInfo.EnumFullName} Value {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>The human-readable description retrieved from description/display attributes.</summary>");
            sb.AppendLine($"{indent}    public string Description {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>The group name specified in DisplayAttribute (for UI categorization).</summary>");
            sb.AppendLine($"{indent}    public string? GroupName {{ get; }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>The numeric representation of the enum value cast to its underlying type.</summary>");
            sb.AppendLine($"{indent}    public {enumInfo.UnderlyingTypeName} UnderlyingValue => ({enumInfo.UnderlyingTypeName})Value;");
            sb.AppendLine();

            // Constructor
            sb.AppendLine($"{indent}    private {enumInfo.WrapperClassName}({enumInfo.EnumFullName} value, string description, string? groupName)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        Value = value;");
            sb.AppendLine($"{indent}        Description = description;");
            sb.AppendLine($"{indent}        GroupName = groupName;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // ToString() override
            sb.AppendLine($"{indent}    public override string ToString() => Description;");
            sb.AppendLine();

            // IEquatable implementation
            sb.AppendLine($"{indent}    public bool Equals({enumInfo.WrapperClassName}? other)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (other is null) return false;");
            sb.AppendLine($"{indent}        if (ReferenceEquals(this, other)) return true;");
            sb.AppendLine($"{indent}        return Value == other.Value;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            sb.AppendLine($"{indent}    public override bool Equals(object? obj) => Equals(obj as {enumInfo.WrapperClassName});");
            sb.AppendLine($"{indent}    public override int GetHashCode() => Value.GetHashCode();");
            sb.AppendLine();

            // Equality operators
            sb.AppendLine($"{indent}    public static bool operator ==({enumInfo.WrapperClassName}? left, {enumInfo.WrapperClassName}? right) => Equals(left, right);");
            sb.AppendLine($"{indent}    public static bool operator !=({enumInfo.WrapperClassName}? left, {enumInfo.WrapperClassName}? right) => !Equals(left, right);");
            sb.AppendLine();

            // Implicit operator to enum type
            sb.AppendLine($"{indent}    public static implicit operator {enumInfo.EnumFullName}({enumInfo.WrapperClassName}? wrapper) => wrapper?.Value ?? default;");
            sb.AppendLine();

            // Static items array
            sb.AppendLine($"{indent}    /// <summary>Provides the sorted, read-only list of all generated enum wrappers.</summary>");
            sb.AppendLine($"{indent}    public static IReadOnlyList<{enumInfo.WrapperClassName}> Items {{ get; }} = new {enumInfo.WrapperClassName}[]");
            sb.AppendLine($"{indent}    {{");
            for (int i = 0; i < enumInfo.Members.Length; i++)
            {
                var member = enumInfo.Members[i];
                var escapedDesc = member.Description.Replace("\\", "\\\\").Replace("\"", "\\\"");
                var escapedGroup = member.GroupName != null ? $"\"{member.GroupName.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"" : "null";
                
                // Copy Member XML Documentation onto each static instantiation
                var memberDocs = FormatXmlDocumentation(member.XmlDocumentation, indent + "        ");
                if (!string.IsNullOrEmpty(memberDocs))
                {
                    sb.Append(memberDocs);
                }
                sb.AppendLine($"{indent}        new {enumInfo.WrapperClassName}({enumInfo.EnumFullName}.{member.Name}, \"{escapedDesc}\", {escapedGroup}),");
            }
            sb.AppendLine($"{indent}    }};");
            sb.AppendLine();

            // Optimized O(1) Index Lookup or Dictionary mapping
            if (enumInfo.IsContiguous)
            {
                sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value in O(1) speed.</summary>");
                sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        int index = (int)value;");
                sb.AppendLine($"{indent}        if (index >= 0 && index < Items.Count)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return Items[index];");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, value.ToString(), null);");
                sb.AppendLine($"{indent}    }}");
            }
            else
            {
                // Caching Dictionary (fallback for non-contiguous or Flags enums)
                sb.AppendLine($"{indent}    private static readonly Dictionary<{enumInfo.EnumFullName}, {enumInfo.WrapperClassName}> _map = new Dictionary<{enumInfo.EnumFullName}, {enumInfo.WrapperClassName}>");
                sb.AppendLine($"{indent}    {{");
                for (int i = 0; i < enumInfo.Members.Length; i++)
                {
                    var member = enumInfo.Members[i];
                    sb.AppendLine($"{indent}        {{ {enumInfo.EnumFullName}.{member.Name}, Items[{i}] }},");
                }
                sb.AppendLine($"{indent}    }};");
                sb.AppendLine();

                if (enumInfo.IsFlags)
                {
                    sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value, supporting combined flags.</summary>");
                    sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        if (_map.TryGetValue(value, out var wrapper))");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return wrapper;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        var desc = ComputeFlagsDescription(value);");
                    sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, desc, null);");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();

                    // Compute flags description dynamic helper
                    sb.AppendLine($"{indent}    private static string ComputeFlagsDescription({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        var parts = new List<string>();");
                    sb.AppendLine($"{indent}        foreach (var item in Items)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            if (item.Value.Equals(default({enumInfo.EnumFullName})))");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                if (value.Equals(default({enumInfo.EnumFullName})))");
                    sb.AppendLine($"{indent}                {{");
                    sb.AppendLine($"{indent}                    return item.Description;");
                    sb.AppendLine($"{indent}                }}");
                    sb.AppendLine($"{indent}                continue;");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}            if ((({enumInfo.UnderlyingTypeName})value & ({enumInfo.UnderlyingTypeName})item.Value) == ({enumInfo.UnderlyingTypeName})item.Value)");
                    sb.AppendLine($"{indent}            {{");
                    sb.AppendLine($"{indent}                parts.Add(item.Description);");
                    sb.AppendLine($"{indent}            }}");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        if (parts.Count > 0)");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return string.Join(\", \", parts);");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        return value.ToString();");
                    sb.AppendLine($"{indent}    }}");
                }
                else
                {
                    sb.AppendLine($"{indent}    /// <summary>Resolves a wrapper instance from its enum value.</summary>");
                    sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} FromValue({enumInfo.EnumFullName} value)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        if (_map.TryGetValue(value, out var wrapper))");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            return wrapper;");
                    sb.AppendLine($"{indent}        }}");
                    sb.AppendLine($"{indent}        return new {enumInfo.WrapperClassName}(value, value.ToString(), null);");
                    sb.AppendLine($"{indent}    }}");
                }
            }
            sb.AppendLine();

            // Smart Parsing: TryParse and Parse
            sb.AppendLine($"{indent}    /// <summary>Attempts to parse a string representation (by description or name) to its wrapper object.</summary>");
            sb.AppendLine($"{indent}    public static bool TryParse(string? text, out {enumInfo.WrapperClassName}? result)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        result = null;");
            sb.AppendLine($"{indent}        if (string.IsNullOrEmpty(text)) return false;");
            sb.AppendLine();
            sb.AppendLine($"{indent}        // 1. Match by Description");
            sb.AppendLine($"{indent}        foreach (var item in Items)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (string.Equals(item.Description, text, StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                result = item;");
            sb.AppendLine($"{indent}                return true;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        // 2. Match by Enum Name");
            sb.AppendLine($"{indent}        foreach (var item in Items)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (string.Equals(item.Value.ToString(), text, StringComparison.OrdinalIgnoreCase))");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                result = item;");
            sb.AppendLine($"{indent}                return true;");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        // 3. Native Enum Parse");
            sb.AppendLine($"{indent}        if (Enum.TryParse<{enumInfo.EnumFullName}>(text, true, out var parsedValue))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            result = FromValue(parsedValue);");
            sb.AppendLine($"{indent}            return true;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        return false;");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            sb.AppendLine($"{indent}    /// <summary>Parses a string representation (by description or name) to its wrapper object.</summary>");
            sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName} Parse(string text)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (TryParse(text, out var result))");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            return result!;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}        throw new ArgumentException($\"Requested value '{{text}}' was not found in {enumInfo.EnumFullName} wrapper.\");");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // Flags specific bitwise helpers
            if (enumInfo.IsFlags)
            {
                sb.AppendLine($"{indent}    /// <summary>Checks if a specific flag is set.</summary>");
                sb.AppendLine($"{indent}    public bool HasFlag({enumInfo.EnumFullName} flag) => Value.HasFlag(flag);");
                sb.AppendLine($"{indent}    /// <summary>Checks if a specific flag is set.</summary>");
                sb.AppendLine($"{indent}    public bool HasFlag({enumInfo.WrapperClassName} wrapper) => wrapper != null && Value.HasFlag(wrapper.Value);");
                sb.AppendLine();

                sb.AppendLine($"{indent}    /// <summary>Flattens the active flags of this combination into separate single wrapper elements.</summary>");
                sb.AppendLine($"{indent}    public IEnumerable<{enumInfo.WrapperClassName}> GetFlags()");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        foreach (var item in Items)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (item.Value.Equals(default({enumInfo.EnumFullName}))) continue;");
                sb.AppendLine($"{indent}            if (HasFlag(item.Value))");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                yield return item;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();
            }

            // TypeConverter implementation
            sb.AppendLine($"{indent}    public class {enumInfo.WrapperClassName}TypeConverter : System.ComponentModel.TypeConverter");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, Type sourceType)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value)");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (value is string str)");
            sb.AppendLine($"{indent}            {{");
            sb.AppendLine($"{indent}                if ({enumInfo.WrapperClassName}.TryParse(str, out var result))");
            sb.AppendLine($"{indent}                {{");
            sb.AppendLine($"                    return result;");
            sb.AppendLine($"                }}");
            sb.AppendLine($"{indent}                throw new ArgumentException($\"Cannot convert '{{str}}' to {enumInfo.WrapperClassName}.\");");
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            return base.ConvertFrom(context, culture, value);");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();

            // Nested JSON Converter (conditional on System.Text.Json dependency)
            if (enumInfo.HasJson)
            {
                sb.AppendLine($"{indent}    public class {enumInfo.WrapperClassName}JsonConverter : System.Text.Json.Serialization.JsonConverter<{enumInfo.WrapperClassName}>");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        public override {enumInfo.WrapperClassName} Read(ref System.Text.Json.Utf8JsonReader reader, Type typeToConvert, System.Text.Json.JsonSerializerOptions options)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (reader.TokenType == System.Text.Json.JsonTokenType.String)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"                var str = reader.GetString();");
                sb.AppendLine($"                if (TryParse(str, out var result))");
                sb.AppendLine($"                {{");
                sb.AppendLine($"                    return result!;");
                sb.AppendLine($"                }}");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            else if (reader.TokenType == System.Text.Json.JsonTokenType.Number)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                if (reader.TryGetInt64(out var num))");
                sb.AppendLine($"{indent}                {{");
                sb.AppendLine($"                    return FromValue(({enumInfo.EnumFullName})num);");
                sb.AppendLine($"{indent}                }}");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            throw new System.Text.Json.JsonException($\"Cannot deserialize {enumInfo.WrapperClassName} from current token.\");");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine();
                sb.AppendLine($"{indent}        public override void Write(System.Text.Json.Utf8JsonWriter writer, {enumInfo.WrapperClassName} value, System.Text.Json.JsonSerializerOptions options)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            if (value == null)");
                sb.AppendLine($"{indent}            {{");
                sb.AppendLine($"{indent}                writer.WriteNullValue();");
                sb.AppendLine($"{indent}                return;");
                sb.AppendLine($"{indent}            }}");
                sb.AppendLine($"{indent}            writer.WriteStringValue(value.Value.ToString());");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}    }}");
            }

            sb.AppendLine($"{indent}}}"); // Class

            // Generate companion WPF IValueConverter (conditional on WPF dependency check)
            if (enumInfo.HasWpf)
            {
                sb.AppendLine();
                sb.AppendLine($"{indent}/// <summary>WPF ValueConverter to map {enumInfo.EnumName} value and {enumInfo.WrapperClassName} back and forth in XAML.</summary>");
                sb.AppendLine($"{indent}public class {enumInfo.WrapperClassName}ToWrapperConverter : System.Windows.Data.IValueConverter");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    /// <summary>Singleton instance of the converter.</summary>");
                sb.AppendLine($"{indent}    public static {enumInfo.WrapperClassName}ToWrapperConverter Instance {{ get; }} = new {enumInfo.WrapperClassName}ToWrapperConverter();");
                sb.AppendLine();
                sb.AppendLine($"{indent}    public object? Convert(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        if (value is {enumInfo.EnumFullName} enumValue)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return {enumInfo.WrapperClassName}.FromValue(enumValue);");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        if (value is string str && {enumInfo.WrapperClassName}.TryParse(str, out var result))");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return result;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return null;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine();
                sb.AppendLine($"{indent}    public object? ConvertBack(object? value, Type targetType, object? parameter, System.Globalization.CultureInfo culture)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        if (value is {enumInfo.WrapperClassName} wrapper)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return wrapper.Value;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        if (value is {enumInfo.EnumFullName} enumValue)");
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine($"{indent}            return enumValue;");
                sb.AppendLine($"{indent}        }}");
                sb.AppendLine($"{indent}        return null;");
                sb.AppendLine($"{indent}    }}");
                sb.AppendLine($"{indent}}}");
            }

            if (hasNamespace)
            {
                sb.AppendLine("}"); // Namespace
            }

            var sourceName = $"{enumInfo.WrapperNamespace}.{enumInfo.WrapperClassName}.g.cs";
            context.AddSource(sourceName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    public sealed class GeneratorResult<T> : IEquatable<GeneratorResult<T>> where T : class, IEquatable<T>
    {
        public T? Value { get; }
        public DiagnosticInfo? Diagnostic { get; }

        public GeneratorResult(T value)
        {
            Value = value;
        }

        public GeneratorResult(DiagnosticInfo diagnostic)
        {
            Diagnostic = diagnostic;
        }

        public bool Equals(GeneratorResult<T>? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return EqualityComparer<T?>.Default.Equals(Value, other.Value) &&
                   EqualityComparer<DiagnosticInfo?>.Default.Equals(Diagnostic, other.Diagnostic);
        }

        public override bool Equals(object? obj) => Equals(obj as GeneratorResult<T>);
        public override int GetHashCode() => (Value, Diagnostic).GetHashCode();
    }

    public sealed class DiagnosticInfo : IEquatable<DiagnosticInfo>
    {
        public string Id { get; }
        public string Message { get; }
        public DiagnosticSeverity Severity { get; }
        public Location Location { get; }

        public DiagnosticInfo(string id, string message, DiagnosticSeverity severity, Location location)
        {
            Id = id;
            Message = message;
            Severity = severity;
            Location = location;
        }

        public bool Equals(DiagnosticInfo? other)
        {
            if (other is null) return false;
            return Id == other.Id && 
                   Message == other.Message && 
                   Severity == other.Severity && 
                   Location.Equals(other.Location);
        }

        public override bool Equals(object? obj) => Equals(obj as DiagnosticInfo);
        public override int GetHashCode() => (Id, Message, Severity, Location).GetHashCode();
    }

    public sealed class EnumToWrapInfo : IEquatable<EnumToWrapInfo>
    {
        public string Namespace { get; }
        public string EnumName { get; }
        public string EnumFullName { get; }
        public string WrapperClassName { get; }
        public string WrapperNamespace { get; }
        public ImmutableArray<EnumMemberInfo> Members { get; }
        public string UnderlyingTypeName { get; }
        public bool IsFlags { get; }
        public bool HasJson { get; }
        public bool IsContiguous { get; }
        public string XmlDocumentation { get; }
        public bool HasWpf { get; }

        public EnumToWrapInfo(
            string @namespace, 
            string enumName, 
            string enumFullName, 
            string wrapperClassName, 
            string wrapperNamespace, 
            List<EnumMemberInfo> members,
            string underlyingTypeName,
            bool isFlags,
            bool hasJson,
            bool isContiguous,
            string xmlDocumentation,
            bool hasWpf)
        {
            Namespace = @namespace;
            EnumName = enumName;
            EnumFullName = enumFullName;
            WrapperClassName = wrapperClassName;
            WrapperNamespace = wrapperNamespace;
            Members = members.ToImmutableArray();
            UnderlyingTypeName = underlyingTypeName;
            IsFlags = isFlags;
            HasJson = hasJson;
            IsContiguous = isContiguous;
            XmlDocumentation = xmlDocumentation;
            HasWpf = hasWpf;
        }

        public bool Equals(EnumToWrapInfo? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return Namespace == other.Namespace &&
                   EnumName == other.EnumName &&
                   EnumFullName == other.EnumFullName &&
                   WrapperClassName == other.WrapperClassName &&
                   WrapperNamespace == other.WrapperNamespace &&
                   UnderlyingTypeName == other.UnderlyingTypeName &&
                   IsFlags == other.IsFlags &&
                   HasJson == other.HasJson &&
                   IsContiguous == other.IsContiguous &&
                   XmlDocumentation == other.XmlDocumentation &&
                   HasWpf == other.HasWpf &&
                   Members.SequenceEqual(other.Members);
        }

        public override bool Equals(object? obj) => Equals(obj as EnumToWrapInfo);

        public override int GetHashCode()
        {
            unchecked
            {
                int hash = 17;
                hash = hash * 23 + Namespace.GetHashCode();
                hash = hash * 23 + EnumName.GetHashCode();
                hash = hash * 23 + EnumFullName.GetHashCode();
                hash = hash * 23 + WrapperClassName.GetHashCode();
                hash = hash * 23 + WrapperNamespace.GetHashCode();
                hash = hash * 23 + UnderlyingTypeName.GetHashCode();
                hash = hash * 23 + IsFlags.GetHashCode();
                hash = hash * 23 + HasJson.GetHashCode();
                hash = hash * 23 + IsContiguous.GetHashCode();
                hash = hash * 23 + XmlDocumentation.GetHashCode();
                hash = hash * 23 + HasWpf.GetHashCode();
                foreach (var member in Members)
                {
                    hash = hash * 23 + member.GetHashCode();
                }
                return hash;
            }
        }
    }

    public sealed class EnumMemberInfo : IEquatable<EnumMemberInfo>
    {
        public string Name { get; }
        public string Description { get; }
        public int? Order { get; }
        public string? GroupName { get; }
        public long NumericValue { get; }
        public string XmlDocumentation { get; }

        public EnumMemberInfo(string name, string description, int? order, string? groupName, long numericValue, string xmlDocumentation)
        {
            Name = name;
            Description = description;
            Order = order;
            GroupName = groupName;
            NumericValue = numericValue;
            XmlDocumentation = xmlDocumentation;
        }

        public bool Equals(EnumMemberInfo? other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;
            return Name == other.Name && 
                   Description == other.Description &&
                   Order == other.Order &&
                   GroupName == other.GroupName &&
                   NumericValue == other.NumericValue &&
                   XmlDocumentation == other.XmlDocumentation;
        }

        public override bool Equals(object? obj) => Equals(obj as EnumMemberInfo);
        public override int GetHashCode() => (Name, Description, Order, GroupName, NumericValue, XmlDocumentation).GetHashCode();
    }
}
