name: Publish to NuGet

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: # Allow manual run from GitHub actions tab

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack Generator
        run: dotnet pack src/EnumWrapper.SourceGenerators/EnumWrapper.SourceGenerators.csproj --configuration Release --no-build --output nupkgs

      - name: Push to NuGet
        shell: bash
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
